### ISSUE TITLE
Unit class in mdo-core

### ISSUE THREAD

**Issue by az-ihsan** [LiUSemWeb/Materials-Design-Ontology#3]
Hi, 

are you sure that you correctly map the Unit class to http://qudt.org/vocab/unit/Unit ? If i may, i would suggest to map it to http://qudt.org/schema/qudt/Unit, like you did in QuantityValue and QuantityKind because the vocab namespace is the collection of the instance of the available unit in QUDT, evenmore the IRI http://qudt.org/vocab/unit/Unit is not resolvable . 

Cheers, 
Ahmad

**Comment by huanyu-li** [comment]
Hi Ahmad,

Thanks for the question! This's a wrong connection to QUDT. We will update MDO shortly

Best,
Huanyu

**Comment by az-ihsan** [comment]
Thank you for the update! Actually i was about to ask you a PR, then it is fine because you already updated.
